### ISSUE TITLE
swaggerPath input not found

### ISSUE THREAD

**Issue by michael-pisman** [diegosanteri/publish-open-api-spec-to-postman#2]
I used the action as documented, but I think `swaggerPath` should be `openApiSpec` ?
```yaml
...
- uses: diegosanteri/publish-open-api-spec-to-postman@v1
        with:
          postmanApiKey: ${{ secrets.POSTMAN_API_KEY }}
          postmanCollectionid: ${{ secrets.POSTMAN_COLLECTION_ID }}
          swaggerPath: openapi.json
```

```
Warning: Unexpected input(s) 'swaggerPath', valid inputs are ['postmanCollectionid', 'postmanApiKey', 'openApiSpec']
```
